version: "3"
services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  vote:
    image: voting-app
    ports:
      - 5010:80

  worker:
    image: worker-app

  result:
    image: result-app
    ports:
      - 5011:80
